home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_page, name = 'home_page'),
    path('register/', views.register, name = 'register'),
    path('login/', views.login_page, name = 'login_page'),
    path('logout/', views.logout_page, name = 'logout_page'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def home_page(request):
    return render(request, 'home_page.html')

def logout_page(request):
    logout(request)
    return redirect('home:login_page')

def login_page(request):
    if(request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        auth = authenticate(request, username = username, password = password)
        if(auth is not None):
            login(request, auth)
            return redirect("home:home_page")
        return render(request, 'login_page.html', { 'errors' : "Invalid username or password"})
    return render(request, 'login_page.html')

def register(request):
    form = UserCreationForm
    if(request.method == 'POST'):
        form = form(request.POST)
        if(form.is_valid()):
            form.save()
            return redirect("home:login_page")
        return render(request, 'register.html', {'form' : form})
    context = {
        'form' : form()
    }
    return render(request, 'register.html', context)

templates/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <div class="container pt-4">
        <div class="text-center mt-5">
            <h1>
                Halo {{ user.username }}
            </h1>
            <a href="{% url 'home:logout_page' %}">
                <button type="submit" class="btn text-center btn-outline-primary">Logout</button>
            </a>
        </div>
    </div>
    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

templates/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="w-100" style="height: 100vh;">
    <div class="container pt-4">
        <div class="row pb-5">
            <div class="offset-md-3 col-md-6 border mt-5">
                {% if errors %}
                    {{ errors }}
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <label for = "username"> Username </label>
                    <input class="form-control" type = "text" name = "username" id = "username">
                    <label for = "password"> Password </label>
                    <input class="form-control" type = "password" name = "password" id = "password">
                    <br>
                    <button type="submit" class="btn text-center btn-outline-primary">Login</button>
                </form>
                <br>
                <a href="/register">
                    <button type="submit" class="btn btn-outline-primary">Register</button>
                </a>
            </div>
        </div>
    </div>
    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body class="w-100" style="height: 100vh;">
    <div class="container pt-4">
        <div class="row pb-5">
            <div class="offset-md-3 col-md-6 border mt-5">    
                {% if form.errors %}
                    {{ form.errors }}
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <label for="id_username">Username:</label><input class="form-control" type="text" name="username" maxlength="150" autofocus="" required="" id="id_username">
                    <label for="id_password1">Password:</label><input class="form-control" type="password" name="password1" required="" id="id_password1">
                    <label for="id_password2">Password confirmation:</label><input class="form-control" type="password" name="password2" required="" id="id_password2">
                    <br>
                    <button type="submit" class="btn text-center btn-outline-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>